"""add asset_master table

Revision ID: 334d798ed54a
Revises: 82b7c7a1e4eb
Create Date: 2026-06-15 11:53:39.442501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334d798ed54a'
down_revision: Union[str, None] = '82b7c7a1e4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smms_asset_code', sa.String(length=50), nullable=True),
    sa.Column('smms_asset_name', sa.String(length=100), nullable=True),
    sa.Column('asset_number_id', sa.String(length=2), nullable=False),
    sa.Column('asset_number_code', sa.String(length=50), nullable=False),
    sa.Column('asset_type_hex', sa.String(length=2), nullable=False),
    sa.Column('gateway_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_type_hex'], ['asset_type_master.asset_type_id'], ),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_id', 'asset_type_hex', 'asset_number_id', name='uq_asset_master_gateway_type_num')
    )
    op.create_index(op.f('ix_asset_master_asset_number_code'), 'asset_master', ['asset_number_code'], unique=False)
    op.create_index(op.f('ix_asset_master_asset_number_id'), 'asset_master', ['asset_number_id'], unique=False)
    op.create_index(op.f('ix_asset_master_asset_type_hex'), 'asset_master', ['asset_type_hex'], unique=False)
    op.create_index(op.f('ix_asset_master_gateway_id'), 'asset_master', ['gateway_id'], unique=False)
    op.create_index(op.f('ix_asset_master_id'), 'asset_master', ['id'], unique=False)
    op.create_index(op.f('ix_asset_master_smms_asset_code'), 'asset_master', ['smms_asset_code'], unique=True)
    op.create_index(op.f('ix_asset_master_station_id'), 'asset_master', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_master_station_id'), table_name='asset_master')
    op.drop_index(op.f('ix_asset_master_smms_asset_code'), table_name='asset_master')
    op.drop_index(op.f('ix_asset_master_id'), table_name='asset_master')
    op.drop_index(op.f('ix_asset_master_gateway_id'), table_name='asset_master')
    op.drop_index(op.f('ix_asset_master_asset_type_hex'), table_name='asset_master')
    op.drop_index(op.f('ix_asset_master_asset_number_id'), table_name='asset_master')
    op.drop_index(op.f('ix_asset_master_asset_number_code'), table_name='asset_master')
    op.drop_table('asset_master')
    # ### end Alembic commands ###
