"""add asset_id to alerts and maintenance, add asset unique constraint

Revision ID: 464fec6f2d1f
Revises: 80e84123e7aa
Create Date: 2026-06-15 14:14:09.083999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464fec6f2d1f'
down_revision: Union[str, None] = '80e84123e7aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_events', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_alert_events_asset_id'), 'alert_events', ['asset_id'], unique=False)
    op.create_foreign_key(None, 'alert_events', 'assets', ['asset_id'], ['id'])
    op.create_unique_constraint('uq_asset_gw_type_number', 'assets', ['station_gateway_id', 'asset_type_hex', 'asset_number_id'])
    op.add_column('maintenance_modes', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_maintenance_modes_asset_id'), 'maintenance_modes', ['asset_id'], unique=False)
    op.create_foreign_key(None, 'maintenance_modes', 'assets', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maintenance_modes', type_='foreignkey')
    op.drop_index(op.f('ix_maintenance_modes_asset_id'), table_name='maintenance_modes')
    op.drop_column('maintenance_modes', 'asset_id')
    op.drop_constraint('uq_asset_gw_type_number', 'assets', type_='unique')
    op.drop_constraint(None, 'alert_events', type_='foreignkey')
    op.drop_index(op.f('ix_alert_events_asset_id'), table_name='alert_events')
    op.drop_column('alert_events', 'asset_id')
    # ### end Alembic commands ###
