"""add_escalation_to_alert_events

Revision ID: 56bb39f8a47c
Revises: d223f9127077
Create Date: 2026-07-07 18:28:02.196886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56bb39f8a47c'
down_revision: Union[str, None] = 'd223f9127077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_events', sa.Column('escalation_level', sa.String(length=20), nullable=True))
    op.add_column('alert_events', sa.Column('escalated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_events', 'escalated_at')
    op.drop_column('alert_events', 'escalation_level')
    # ### end Alembic commands ###
