"""align assets model with exact user spec

Revision ID: 64311d435e57
Revises: b82641dd11e7
Create Date: 2026-06-15 13:49:46.588024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64311d435e57'
down_revision: Union[str, None] = 'b82641dd11e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_assets_asset_number_code', table_name='assets')
    op.drop_index('ix_assets_asset_number_id', table_name='assets')
    op.drop_index('ix_assets_asset_type_hex', table_name='assets')
    op.drop_index('ix_assets_id', table_name='assets')
    op.drop_index('ix_assets_smms_asset_code', table_name='assets')
    op.drop_index('ix_assets_station_gateway_id', table_name='assets')
    op.drop_index('ix_assets_station_id', table_name='assets')
    op.create_unique_constraint(None, 'assets', ['smms_asset_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='unique')
    op.create_index('ix_assets_station_id', 'assets', ['station_id'], unique=False)
    op.create_index('ix_assets_station_gateway_id', 'assets', ['station_gateway_id'], unique=False)
    op.create_index('ix_assets_smms_asset_code', 'assets', ['smms_asset_code'], unique=True)
    op.create_index('ix_assets_id', 'assets', ['id'], unique=False)
    op.create_index('ix_assets_asset_type_hex', 'assets', ['asset_type_hex'], unique=False)
    op.create_index('ix_assets_asset_number_id', 'assets', ['asset_number_id'], unique=False)
    op.create_index('ix_assets_asset_number_code', 'assets', ['asset_number_code'], unique=False)
    op.alter_column('assets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
