"""Add equipment_rooms table

Revision ID: 7d2a8d642107
Revises: e8eb8e29ee31
Create Date: 2026-06-09 11:35:16.745101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2a8d642107'
down_revision: Union[str, None] = 'e8eb8e29ee31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=10), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'room_type', name='uq_station_room_type')
    )
    op.create_index(op.f('ix_equipment_rooms_id'), 'equipment_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_rooms_station_id'), 'equipment_rooms', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_rooms_station_id'), table_name='equipment_rooms')
    op.drop_index(op.f('ix_equipment_rooms_id'), table_name='equipment_rooms')
    op.drop_table('equipment_rooms')
    # ### end Alembic commands ###
