"""drop asset master table

Revision ID: 80e84123e7aa
Revises: 64311d435e57
Create Date: 2026-06-15 13:59:06.247944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80e84123e7aa'
down_revision: Union[str, None] = '64311d435e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_asset_master_asset_number_code', table_name='asset_master')
    op.drop_index('ix_asset_master_asset_number_id', table_name='asset_master')
    op.drop_index('ix_asset_master_asset_type_hex', table_name='asset_master')
    op.drop_index('ix_asset_master_gateway_id', table_name='asset_master')
    op.drop_index('ix_asset_master_id', table_name='asset_master')
    op.drop_index('ix_asset_master_smms_asset_code', table_name='asset_master')
    op.drop_index('ix_asset_master_station_id', table_name='asset_master')
    op.drop_table('asset_master')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('smms_asset_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('smms_asset_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('asset_number_id', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('asset_number_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('asset_type_hex', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('gateway_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('make', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_type_hex'], ['asset_type_master.asset_type_id'], name='asset_master_asset_type_hex_fkey'),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.id'], name='asset_master_gateway_id_fkey'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name='asset_master_station_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='asset_master_pkey'),
    sa.UniqueConstraint('gateway_id', 'asset_type_hex', 'asset_number_id', name='uq_asset_master_gateway_type_num')
    )
    op.create_index('ix_asset_master_station_id', 'asset_master', ['station_id'], unique=False)
    op.create_index('ix_asset_master_smms_asset_code', 'asset_master', ['smms_asset_code'], unique=True)
    op.create_index('ix_asset_master_id', 'asset_master', ['id'], unique=False)
    op.create_index('ix_asset_master_gateway_id', 'asset_master', ['gateway_id'], unique=False)
    op.create_index('ix_asset_master_asset_type_hex', 'asset_master', ['asset_type_hex'], unique=False)
    op.create_index('ix_asset_master_asset_number_id', 'asset_master', ['asset_number_id'], unique=False)
    op.create_index('ix_asset_master_asset_number_code', 'asset_master', ['asset_number_code'], unique=False)
    # ### end Alembic commands ###
