"""add assets table

Revision ID: b82641dd11e7
Revises: 334d798ed54a
Create Date: 2026-06-15 12:41:27.980776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82641dd11e7'
down_revision: Union[str, None] = '334d798ed54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smms_asset_code', sa.String(length=50), nullable=False),
    sa.Column('smms_asset_name', sa.String(length=100), nullable=False),
    sa.Column('asset_number_code', sa.String(length=50), nullable=False),
    sa.Column('asset_number_id', sa.String(length=2), nullable=False),
    sa.Column('asset_type_hex', sa.String(length=2), nullable=False),
    sa.Column('station_gateway_id', sa.String(length=8), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('attr1', sa.String(length=100), nullable=True),
    sa.Column('attr2', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_type_hex'], ['asset_type_master.asset_type_id'], ),
    sa.ForeignKeyConstraint(['station_gateway_id'], ['gateways.stngw_id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_number_code'), 'assets', ['asset_number_code'], unique=False)
    op.create_index(op.f('ix_assets_asset_number_id'), 'assets', ['asset_number_id'], unique=False)
    op.create_index(op.f('ix_assets_asset_type_hex'), 'assets', ['asset_type_hex'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_smms_asset_code'), 'assets', ['smms_asset_code'], unique=True)
    op.create_index(op.f('ix_assets_station_gateway_id'), 'assets', ['station_gateway_id'], unique=False)
    op.create_index(op.f('ix_assets_station_id'), 'assets', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_station_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_station_gateway_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_smms_asset_code'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type_hex'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_number_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_number_code'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
