"""add_is_processed_to_telemetry

Revision ID: d223f9127077
Revises: 1189e790771b
Create Date: 2026-07-07 18:26:05.616841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd223f9127077'
down_revision: Union[str, None] = '1189e790771b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('is_processed', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_telemetry_is_processed'), 'telemetry', ['is_processed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_is_processed'), table_name='telemetry')
    op.drop_column('telemetry', 'is_processed')
    # ### end Alembic commands ###
